apiVersion: v1
kind: Service
metadata:
  name: dispatch
  namespace: roboshop
spec:
  selector:
    app: dispatch
    project: roboshop
  ports:
  - protocol: TCP
    port: 5672 #service-port
    targetPort: 5672 #container-port